const videoData = [
    // GIAO TIẾP TRẢI NGHIỆM
    { id: 1, title: "Trải Nghiệm - DAY 2", url: "https://www.youtube.com/embed/GJhMRKTWA6s" },
    { id: 2, title: "Trải Nghiệm - DAY 3", url: "https://www.youtube.com/embed/cC1feBI2buE" },
    { id: 3, title: "Trải Nghiệm - DAY 4", url: "https://www.youtube.com/embed/nClV-VOR9Bk" },
    { id: 4, title: "Trải Nghiệm - DAY 5", url: "https://www.youtube.com/embed/oM5t_Rr0-UY" },
    { id: 5, title: "Trải Nghiệm - DAY 6", url: "https://www.youtube.com/embed/i5r_KuRtCB8" },
    { id: 6, title: "Trải Nghiệm - DAY 7", url: "https://www.youtube.com/embed/3gXZ4DIluPs" },
    { id: 7, title: "Trải Nghiệm - DAY 8", url: "https://www.youtube.com/embed/bIGm0k6uWzE" },
    { id: 8, title: "Trải Nghiệm - DAY 10", url: "https://www.youtube.com/embed/OAExMgbfGL0" },
    { id: 9, title: "Trải Nghiệm - DAY 11", url: "https://www.youtube.com/embed/b5D-UYut6FU" },
    { id: 10, title: "Trải Nghiệm - DAY 12", url: "https://www.youtube.com/embed/eHWQu0A6JKo" },
    { id: 11, title: "Trải Nghiệm - DAY 13", url: "https://www.youtube.com/embed/K2oXkC1Lw3w" },
    { id: 12, title: "Trải Nghiệm - DAY 14", url: "https://www.youtube.com/embed/nK_vpS0qYlY" },
    { id: 13, title: "Trải Nghiệm - DAY 16", url: "https://www.youtube.com/embed/BdAhSJPJJVc" },
    { id: 14, title: "Trải Nghiệm - DAY 17", url: "https://www.youtube.com/embed/ZAm9gfeMaKU" },
    { id: 15, title: "Trải Nghiệm - DAY 18", url: "https://www.youtube.com/embed/AonV3eFEgUw" },
    { id: 16, title: "Trải Nghiệm - DAY 19", url: "https://www.youtube.com/embed/01LD_dK7cs0" },
    { id: 17, title: "Trải Nghiệm - DAY 20", url: "https://www.youtube.com/embed/01LD_dK7cs0" },
    { id: 18, title: "Trải Nghiệm - DAY 22, 23", url: "https://www.youtube.com/embed/QCv-UbAmcsY" },
    { id: 19, title: "Trải Nghiệm - DAY 24", url: "https://www.youtube.com/embed/DHJ0VxhjEVc" },
    { id: 20, title: "Trải Nghiệm - DAY 25", url: "https://www.youtube.com/embed/G0_WbiLu1EY" },
    { id: 21, title: "Trải Nghiệm - DAY 26", url: "https://www.youtube.com/embed/YOZcErqtzPg" },
    { id: 22, title: "Trải Nghiệm - DAY 27", url: "https://www.youtube.com/embed/lcW6ECzGthQ" },
    { id: 23, title: "Trải Nghiệm - DAY 28", url: "https://www.youtube.com/embed/WjziFHhWPEM" },
    { id: 24, title: "Trải Nghiệm - DAY 29", url: "https://www.youtube.com/embed/lwaMbiS-DL4" },

    // GIAO TIẾP THỰC CHIẾN
    { id: 25, title: "Thực Chiến - DAY 1", url: "https://www.youtube.com/embed/JhcjMk7X88E" },
    { id: 26, title: "Thực Chiến - DAY 2", url: "https://www.youtube.com/embed/T9LhGzt4Pxc" },
    { id: 27, title: "Thực Chiến - DAY 3", url: "https://www.youtube.com/embed/Szdup2Ivajg" },
    { id: 28, title: "Thực Chiến - DAY 5", url: "https://www.youtube.com/embed/MiOs1ZQJ6Kk" },
    { id: 29, title: "Thực Chiến - DAY 6", url: "https://www.youtube.com/embed/Jik_vQBJtZY" },
    { id: 30, title: "Thực Chiến - DAY 7", url: "https://www.youtube.com/embed/I1re410WBrg" },
    { id: 31, title: "Thực Chiến - DAY 9", url: "https://www.youtube.com/embed/qRd4-6bYknQ" },
    { id: 32, title: "Thực Chiến - DAY 10", url: "https://www.youtube.com/embed/sQSq2nCBzJI" },
    { id: 33, title: "Thực Chiến - DAY 11", url: "https://www.youtube.com/embed/BDAseYkxX14" },
    { id: 34, title: "Thực Chiến - DAY 13", url: "https://www.youtube.com/embed/IAVyzbLvfCI" },
    { id: 35, title: "Thực Chiến - DAY 14", url: "https://www.youtube.com/embed/aaSH5OGUa1U" },
    { id: 36, title: "Thực Chiến - DAY 16", url: "https://www.youtube.com/embed/MDFc1Cul97c" },
    { id: 37, title: "Thực Chiến - DAY 17", url: "https://www.youtube.com/embed/fvny3voOJLk" },
    { id: 38, title: "Thực Chiến - DAY 19", url: "https://www.youtube.com/embed/nwtoEG6VF28" },
    { id: 39, title: "Thực Chiến - DAY 20", url: "https://www.youtube.com/embed/DRAB2RTTth4" },
    { id: 40, title: "Thực Chiến - DAY 22", url: "https://www.youtube.com/embed/u_6CUTX906I" },
    { id: 41, title: "Thực Chiến - DAY 23", url: "https://www.youtube.com/embed/M7mx7El2eH4" },
    { id: 42, title: "Thực Chiến - DAY 24", url: "https://www.youtube.com/embed/ronJ29gxHQg" },
    { id: 43, title: "Thực Chiến - DAY 26", url: "https://www.youtube.com/embed/Le14Wg5L7pA" },
    { id: 44, title: "Thực Chiến - DAY 27", url: "https://www.youtube.com/embed/og1edX9ELl4" },
    { id: 45, title: "Thực Chiến - DAY 28", url: "https://www.youtube.com/embed/sRu4V6kPAh8" },
    { id: 46, title: "Thực Chiến - DAY 30", url: "https://www.youtube.com/embed/BtT16a5abyc" },
    { id: 47, title: "Thực Chiến - DAY 31", url: "https://www.youtube.com/embed/wI_dLuov9WQ" },
    { id: 48, title: "Thực Chiến - DAY 32", url: "https://www.youtube.com/embed/21pODUnF5Rw" },
    { id: 49, title: "Thực Chiến - DAY 34", url: "https://www.youtube.com/embed/0uZw1SMlQmY" },
    { id: 50, title: "Thực Chiến - DAY 35", url: "https://www.youtube.com/embed/OjWHxiYctkQ" },
    { id: 51, title: "Thực Chiến - DAY 36", url: "https://www.youtube.com/embed/0xKiZ2avqc0" },
    { id: 52, title: "Thực Chiến - DAY 38", url: "https://www.youtube.com/embed/lsDoU_tP3Kw" },
    { id: 53, title: "Thực Chiến - DAY 39", url: "https://www.youtube.com/embed/ywh6mlMkRPQ" },
    { id: 54, title: "Thực Chiến - DAY 40", url: "https://www.youtube.com/embed/F8jr6SypEeg" }
];
